# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Admin.create(name: 'Long Dang', email:'abc@abc.com', password: '123456' , password_confirmation: '123456', tel:'0123456789')

FeeUnit.create(name: 'Triệu/Tháng', admin_id: 1)
FeeUnit.create(name: 'Nghìn USD/Tháng', admin_id: 1)

RentalFee.create(price: 1, fee_unit_id: 2, admin_id: 1)
RentalFee.create(price: 2, fee_unit_id: 2, admin_id: 1)
RentalFee.create(price: 3, fee_unit_id: 2, admin_id: 1)
RentalFee.create(price: 4, fee_unit_id: 2, admin_id: 1)
RentalFee.create(price: 5, fee_unit_id: 2, admin_id: 1)
RentalFee.create(price: 10, fee_unit_id: 1, admin_id: 1)
RentalFee.create(price: 20, fee_unit_id: 1, admin_id: 1)
RentalFee.create(price: 30, fee_unit_id: 1, admin_id: 1)
RentalFee.create(price: 40, fee_unit_id: 1, admin_id: 1)
RentalFee.create(price: 50, fee_unit_id: 1, admin_id: 1)

ManagementFee.create(price: 1, fee_unit_id: 2, admin_id: 1)
ManagementFee.create(price: 2, fee_unit_id: 2, admin_id: 1)
ManagementFee.create(price: 3, fee_unit_id: 2, admin_id: 1)
ManagementFee.create(price: 4, fee_unit_id: 2, admin_id: 1)
ManagementFee.create(price: 5, fee_unit_id: 2, admin_id: 1)
ManagementFee.create(price: 10, fee_unit_id: 1, admin_id: 1)
ManagementFee.create(price: 20, fee_unit_id: 1, admin_id: 1)
ManagementFee.create(price: 30, fee_unit_id: 1, admin_id: 1)
ManagementFee.create(price: 40, fee_unit_id: 1, admin_id: 1)
ManagementFee.create(price: 50, fee_unit_id: 1, admin_id: 1)

Building.create(name: 'Landmark 81', build_year: 2012, address: "81 Nguyen Huu Canh Street", district: "Quận Bình Thạnh", city: "Hồ Chí Minh", floor_number: 81, equipments: "Full equipments", admin_id: 1)
Building.create(name: 'Petronas Tower', build_year: 2010, address: "35 Nguyen Hue Street", district: "Quận 1", city: "Hồ Chí Minh", floor_number: 20, equipments: "Full equipments", admin_id: 1)
Building.create(name: 'Ruby Tower', build_year: 2002, address: "135 Le Van Kiet Street", district: "Quận 5", city: "Hồ Chí Minh", floor_number: 12, equipments: "Full equipments", admin_id: 1)
Building.create(name: 'Bitexco Tower', build_year: 2008, address: "380 Nguyen Thi Minh Khai Street", district: "Quận 3", city: "Hồ Chí Minh", floor_number: 60, equipments: "Full equipments", admin_id: 1)
Building.create(name: 'Metro Building', build_year: 2012, address: "8 Võ Thị Sáu Street", district: "Quận 3", city: "Hồ Chí Minh", floor_number: 18, equipments: "Full equipments", admin_id: 1)
Building.create(name: 'Millenium Building', build_year: 2000, address: "148 Lê Thánh Tôn Street", district: "Quận 1", city: "Hồ Chí Minh", floor_number: 8, equipments: "Full equipments", admin_id: 1)

Floor.create(building_id: 1, floor_num: 20, total_room: 5, admin_id: 1)
Floor.create(building_id: 1, floor_num: 30, total_room: 4, admin_id: 1)
Floor.create(building_id: 1, floor_num: 40, total_room: 6, admin_id: 1)
Floor.create(building_id: 1, floor_num: 50, total_room: 2, admin_id: 1)
Floor.create(building_id: 1, floor_num: 60, total_room: 3, admin_id: 1)
Floor.create(building_id: 1, floor_num: 70, total_room: 1, admin_id: 1)

Floor.create(building_id: 2, floor_num: 2, total_room: 5, admin_id: 1)
Floor.create(building_id: 2, floor_num: 3, total_room: 4, admin_id: 1)
Floor.create(building_id: 2, floor_num: 4, total_room: 6, admin_id: 1)
Floor.create(building_id: 2, floor_num: 5, total_room: 2, admin_id: 1)
Floor.create(building_id: 2, floor_num: 6, total_room: 3, admin_id: 1)
Floor.create(building_id: 2, floor_num: 7, total_room: 1, admin_id: 1)

Floor.create(building_id: 3, floor_num: 2, total_room: 5, admin_id: 1)
Floor.create(building_id: 3, floor_num: 3, total_room: 4, admin_id: 1)
Floor.create(building_id: 3, floor_num: 4, total_room: 6, admin_id: 1)
Floor.create(building_id: 3, floor_num: 5, total_room: 2, admin_id: 1)
Floor.create(building_id: 3, floor_num: 6, total_room: 3, admin_id: 1)
Floor.create(building_id: 3, floor_num: 7, total_room: 1, admin_id: 1)

Floor.create(building_id: 4, floor_num: 2, total_room: 5, admin_id: 1)
Floor.create(building_id: 4, floor_num: 3, total_room: 4, admin_id: 1)
Floor.create(building_id: 4, floor_num: 4, total_room: 6, admin_id: 1)
Floor.create(building_id: 4, floor_num: 5, total_room: 2, admin_id: 1)
Floor.create(building_id: 4, floor_num: 6, total_room: 3, admin_id: 1)
Floor.create(building_id: 4, floor_num: 7, total_room: 1, admin_id: 1)

Floor.create(building_id: 5, floor_num: 2, total_room: 5, admin_id: 1)
Floor.create(building_id: 5, floor_num: 3, total_room: 4, admin_id: 1)
Floor.create(building_id: 5, floor_num: 4, total_room: 6, admin_id: 1)
Floor.create(building_id: 5, floor_num: 5, total_room: 2, admin_id: 1)
Floor.create(building_id: 5, floor_num: 6, total_room: 3, admin_id: 1)
Floor.create(building_id: 5, floor_num: 7, total_room: 1, admin_id: 1)

Floor.create(building_id: 6, floor_num: 2, total_room: 5, admin_id: 1)
Floor.create(building_id: 6, floor_num: 3, total_room: 4, admin_id: 1)
Floor.create(building_id: 6, floor_num: 4, total_room: 6, admin_id: 1)
Floor.create(building_id: 6, floor_num: 5, total_room: 2, admin_id: 1)
Floor.create(building_id: 6, floor_num: 6, total_room: 3, admin_id: 1)
Floor.create(building_id: 6, floor_num: 7, total_room: 1, admin_id: 1)

Room.create(admin_id: 1, floor_id: 15, acreage: 20, room_num: 1, rental_fee_id: 2, management_fee_id: 8)
Room.create(admin_id: 1, floor_id: 15, acreage: 26, room_num: 2, rental_fee_id: 4, management_fee_id: 10)
Room.create(admin_id: 1, floor_id: 10, acreage: 15.5, room_num: 1, rental_fee_id: 10, management_fee_id: 10)
Room.create(admin_id: 1, floor_id: 10, acreage: 32.3, room_num: 2, rental_fee_id: 5, management_fee_id: 5)
Room.create(admin_id: 1, floor_id: 10, acreage: 16.8, room_num: 3, rental_fee_id: 3, management_fee_id: 3)
Room.create(admin_id: 1, floor_id: 3, acreage: 20.78, room_num: 1, rental_fee_id: 5, management_fee_id: 8)
Room.create(admin_id: 1, floor_id: 1, acreage: 22.33, room_num: 2, rental_fee_id: 4, management_fee_id: 1)
Room.create(admin_id: 1, floor_id: 5, acreage: 26.7, room_num: 1, rental_fee_id: 8, management_fee_id: 4)
Room.create(admin_id: 1, floor_id: 20, acreage: 20.25, room_num: 1, rental_fee_id: 9, management_fee_id: 7)
Room.create(admin_id: 1, floor_id: 30, acreage: 25.5, room_num: 1, rental_fee_id: 7, management_fee_id: 6)
Room.create(admin_id: 1, floor_id: 19, acreage: 23.6, room_num: 1, rental_fee_id: 4, management_fee_id: 3)
Room.create(admin_id: 1, floor_id: 8, acreage: 22.75, room_num: 1, rental_fee_id: 6, management_fee_id: 2)
Room.create(admin_id: 1, floor_id: 25, acreage: 19.88, room_num: 1, rental_fee_id: 5, management_fee_id: 9)
Room.create(admin_id: 1, floor_id: 16, acreage: 23.15, room_num: 1, rental_fee_id: 1, management_fee_id: 5)